name: flutter_application
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dart_date: "1.2.2"
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1
  in_app_purchase: ^3.1.13
  in_app_purchase_android: ^0.3.0+17
  in_app_purchase_storekit: ^0.3.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
